AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  EZAuditLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: handler
      CodeUri: .
      Handler: app.handler
      Runtime: nodejs18.x
      Description: ""
      Layers:
        - !Ref ChromiumLayer
        - !Ref LighthouseLayer
        - !Ref PuppeteerLayer
      MemorySize: 2048
      Timeout: 60

  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: chromium
      Description: AWS NPM Dependencies
      ContentUri: "chromium/nodejs"
      CompatibleRuntimes:
        - nodejs18.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

  LighthouseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lighthouse
      Description: AWS NPM Dependencies
      ContentUri: "lighthouse/nodejs"
      CompatibleRuntimes:
        - nodejs18.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

  PuppeteerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: puppeteer
      Description: AWS NPM Dependencies
      ContentUri: "puppeteer/nodejs"
      CompatibleRuntimes:
        - nodejs18.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain
